version: '2.2'
services:
  metaworld-ci:
    build:
      cache_from:
        - ryanjulian/metaworld-ci:latest
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - PARENT_IMAGE=rlworkgroup/garage-headless
    image: ${TAG}
